### ISSUE TITLE
Comparison with Sender-selected Distribution (`cc/bcc` headers)

### ISSUE THREAD

**Issue by aksh1618** [whitfin/rabbitmq-delimiter-exchange#9]
Hi there! I've been tackling a problem that somewhat lies in a similar problem space as the one you describe in [Achieving Multiple Routing Keys in RabbitMQ Exchanges](https://whitfin.io/blog/multiple-routing-keys-in-rabbitmq-exchanges/), with the additional requirement that a consumer could be handling multiple clients. However, before discovering this blog post, I bumped into [Sender-selected Distribution](https://www.rabbitmq.com/docs/sender-selected) in RabbitMQ docs, which seemed suitable for my use case. However, I could think of one possible caveat of using this:
- Setup: Queue `Q1` bound to exchange with routing keys `client1` & `client2` on Exchange `E`
- Scenario: Publisher publishes a message `m1` to `E` with routing key `client1` and header `cc: [client2]`
- Requirement: `m1` routed to `Q1` once
- Actual (or rather feared, as of now): `m1` routed to `Q1` twice

To verify that the requirement is fulfilled and the message isn't duplicated, I decided to try my luck with some AI assistants before going for real testing. Although nothing conclusive came out of them, one of them pointed to `x-delimiter`, which led me to your blog post!

Although I'm planning to test out the above scenario on a real instance soon, I'm also wondering whether this scenario is indeed the difference between using the `cc/bcc` headers vs using the `x-delimiter` exchange. Could you comment on this as well as any other differences that led you to creating the `x-delimiter` exchange instead of using `cc/bcc` headers extension provided by RabbitMQ?

**Comment by whitfin** [comment]
Hi @aksh1618 :)

The shortest answer is that performance was a concern and I wanted the smallest amount of overhead above a `direct` exchange as possible. Given this, the initial state of this plugin literally just split the routing key and passed it onto the `direct` exchange - in theory skipping everything around headers; no modification, no scanning the headers list, etc.

> Although nothing conclusive came out of them, one of them pointed to x-delimiter, which led me to your blog post!

I can confirm that this exchange works for your use case above:

* Publisher `P` produces a Message `M` to Exchange `E` with a routing key `:client1:client2` (for example)
* Exchange `E` splits on `:` and directs to `client1` and `client2` queues.
* Given Queue `Q` is listening on `client1` and/or `client2`, `M` is placed in `Q`. I can confirm that this only places a single copy inside `Q`, regardless of how many bindings match (this was my exact initial use case).

Whether this is true or not for `sender-selection`, I'm not sure. I've never really used it for anything. I went for a quick look through the code and I expect that it _is_ true, because there's only a single message instance associated with multiple keys. I haven't tested this to confirm though.

> Could you comment on this as well as any other differences that led you to creating the x-delimiter exchange instead of using cc/bcc headers extension provided by RabbitMQ?

A slightly longer answer is that it was so easy to write my own exchange for this that it made it much easier to test. Having never worked with the `sender-selection` before, it might impose other requirements I wasn't aware of. Making this exchange kept it much simpler and reduced our surface area (literally, the only change was a string split). It was extremely simple to reason about, nothing to learn, etc. It also uses a single field of the message, rather than splitting across routing key and headers (which I think is actually an important note).

It's been a long time since I wrote this exchange and RabbitMQ has people working on it much more frequently. It's definitely possible at this point that `cc/bcc` has minimal overhead and could indeed be used instead of this exchange. If your testing does actually show this to be the case, I'm happy to drop a deprecation on here and recommend people use it instead. If I get time I might actually investigate myself too, maybe together we can bring my post up to date if it needs changes.

To be clear I'm pretty sure this implementation will _always_ be faster because it doesn't touch headers at all, but maybe the header logic exists outside of the exchange at this point so the penalty there is felt here regardless - thus making this exchange redundant. Given the quick glance I just had, I have a sneaky feeling this could be the case.

**Comment by aksh1618** [comment]
Thanks for taking the time to do this @whitfin, really appreciate it! I went through the article, love the procedural format and the addition of benchmark results, it's now an even more interesting a read! I feel the x-delimiter exchange is still a great alternative (especially given that 3.13 has basically *just* released, and will definitely take some time to get wider adoption), and also serves as an elegant RabbitMQ plugin example implementation for adding a custom exchange type. I definitely learned a lot, thanks again!
